server:
  port: 6620
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://db-wuyuan-pl.cxxl3m4nwvxk.eu-west-3.rds.amazonaws.com:3306/test?useUnicode=true&useSSL=false&characterEncoding=utf8
      username: admin
      password: Wuyuan%2021#pL
      initial-size: 5
      max-active: 5
      max-wait: 5000
